# Week 10: Midterm review

In [1]:
import numpy as np
import pandas as pd

### Q1. Access list

In [2]:
a = ['a', 0, 'bc']
a[2]

'bc'

### Q2. Addition of two numpy array

In [3]:
b = np.array([1,2,3])
c = np.array([1,2,3])

In [4]:
print(b+c)

[2 4 6]


### Q3. Addition of two lists

In [5]:
B = [1, 2, 3]
C = [1, 2, 3]

In [6]:
print(B+C)

[1, 2, 3, 1, 2, 3]


### Q4. Addition of two sets

In [7]:
A = {1, 2, 3}
B = {1, 2, 3}

In [8]:
# operator + does not apply to addition of two sets
# union method does similar job, but repeated elements will not be counted.
print(A+B)

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [9]:
print(A.union(B))

{1, 2, 3}


### Q5. Set comprehension

In [10]:
# Elegant way to make a desired list, set, dictionary, etc.

{s for s in [2,4,6,8,10]}.union({m for m in [3,6,9]})

{2, 3, 4, 6, 8, 9, 10}

### Q6. Dictionary comprehension and zip

In [11]:
a = ['p', 'q', 'r'] 
b = np.array([1,2,3])

{u:v for (u,v) in zip(a,b**2)}

{'p': 1, 'q': 4, 'r': 9}

### Q7. Bitwise shift operation

In [12]:
3 << 3

24

### Q8. Which one of the following daily applications belongs to the supervised learning
 - (a) Bitcoin price prediction
 - (b) Sentence auto-completion
 - (c) Video recommender in youtube
 - (d) Data visualization

### Q9. Which of the following is not true about the MNIST data set.
 - (a) It is only useful for training supervised learning models
 - (b) It is a data set with x = image of handwritten digit and y = integer corresponding to the digit
 - (c) The image of digit has 8x8 pixels.
 - (d) One of the popular models for predicting the label of an unseen image is neural network.

### Q10. Which datum contributes the most to the squared error? 

In [81]:
from sklearn.metrics import mean_squared_error

In [82]:
adv_true = np.array([20, 98, 220])
adv_pred = np.array([34, 110, 210])

In [83]:
mean_squared_error(adv_true, adv_pred)

146.66666666666666

In [84]:
mean_squared_error(adv_true, adv_pred, sample_weight=np.array([1,0,0]))

196.0

In [85]:
mean_squared_error(adv_true, adv_pred, sample_weight=np.array([0,1,0]))

144.0

In [86]:
mean_squared_error(adv_true, adv_pred, sample_weight=np.array([0,0,1]))

100.0

### Q11. Accessing tablular data in pandas

In [13]:
data = pd.read_csv('Advertising.csv')

In [14]:
data.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

### To calculate the mean of 'TV' column in the first 100 rows 

In [16]:
data.iloc[:100]['TV'].mean()

147.1649999999999

### Q12. Find the maximum value in 'Sales' column

In [17]:
data['Sales'].max()

27.0

In [18]:
data.loc[:,'Sales'].max()

27.0

### Q13. Logistic function $f(x)=\frac{1}{1+e^{-ax-b}}$

### Q14. Cross entropy

### In classification task, the data set consists of a group of paired (x,y) with numeric $x$ and binary $y$. In default data set, $x$ is the balance while $y$ is the status of default ($y$=1) or not ($y$=0). The goal is to find a function $f(x)=\frac{1}{1+e^{-ax-b}}$ so we can make the prediction on $y$. The cross entropy is defined as $CE=-[y\log f + (1-y)\log (1-f)]$. (Note the true CE is obtained after averaging)

### Q15. Which datum contributes the most to the cross entropy?

In [19]:
from sklearn.metrics import log_loss

In [33]:
pred = np.array([0.01, 0.4, 0.99])
y_true = np.array([0, 0, 1])

In [34]:
log_loss(y_true, pred)

0.1769754318243312

In [87]:
log_loss(y_true, pred, sample_weight=np.array([1,0,0]))

0.01005033585350145

In [88]:
log_loss(y_true, pred, sample_weight=np.array([0,1,0]))

0.5108256237659907

In [89]:
log_loss(y_true, pred, sample_weight=np.array([0,0,1]))

0.01005033585350145

### Q16. For the Auto data set and we are interested in the relation between MPG and horse power, if we use a linear model and a cubic model, then the cubic model shall result in a higher bias. Ans: false.

In [125]:
auto = pd.read_csv('Auto.csv', na_values='?').dropna()

x_auto = auto.horsepower.values.reshape(-1,1)
y_auto = auto.mpg.values

In [126]:
import sklearn.linear_model as skl_lm

from mlxtend.evaluate import bias_variance_decomp

In [128]:
# linear model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

degree = 1

poly = PolynomialFeatures(degree)

x_poly = poly.fit_transform(x_auto)

X_train, X_test, y_train, y_test = train_test_split(x_poly, y_auto, test_size=0.5, random_state=1)

model = skl_lm.LinearRegression()

mseV, biasV, varV = bias_variance_decomp(model, X_train, y_train, X_test, y_test, loss='mse', num_rounds=200, random_seed=1)

print(mseV, biasV, varV)

25.114940557652258 24.833687992119717 0.28125256553253186


In [129]:
# cubic model
degree = 3

poly = PolynomialFeatures(degree)

x_poly = poly.fit_transform(x_auto)

X_train, X_test, y_train, y_test = train_test_split(x_poly, y_auto, test_size=0.5, random_state=1)

model = skl_lm.LinearRegression()

mseV, biasV, varV = bias_variance_decomp(model, X_train, y_train, X_test, y_test, loss='mse', num_rounds=200, random_seed=1)

print(mseV, biasV, varV)

19.072643320591023 18.75066829072233 0.3219750298686828


In [131]:
# bias for linear model is 24.8 while bias for cubic model is 18.8. so linear model has larger bias!

### Q17. Following the previous question, the linear model shall result in lower variance if we talk about the estimated test error. Ans: True.

In [132]:
# From above 2 cells, varinace for linear model is 0.28 while variance for cubic one is 0.32. 

### Q18. We talked about bias variance tradeoff in the example using 50/50 split of training and test subset, in the following options, which one can lead to reduced variance? Ans. Chose 90/10 ratio between training/test sizes.

In [130]:
degree = 3

poly = PolynomialFeatures(degree)

x_poly = poly.fit_transform(x_auto)

X_train, X_test, y_train, y_test = train_test_split(x_poly, y_auto, test_size=0.1, random_state=1)

model = skl_lm.LinearRegression()

mseV, biasV, varV = bias_variance_decomp(model, X_train, y_train, X_test, y_test, loss='mse', num_rounds=200, random_seed=1)

print(mseV, biasV, varV)

17.359077830968232 17.16942056781327 0.1896572631549533


### Q19 -- Q23

In [44]:
default = pd.read_csv('Default.csv')

### How many customers are default? $N_1$

In [58]:
len(default.loc[default['default']=='Yes'])

333

### How many customers are not default? $N_0$

In [59]:
len(default.loc[default['default']=='No'])

9667

### How to calculate the average of balance $\mu_0$ for non-default customers, $\mu_1$ for default customers, the variance of balance $\sigma_0^2$ for non-default customers, and $\sigma_1^2$ for default customers?

## $\mu_1$

In [47]:
default.loc[default['default']=='Yes']['balance'].mean()

1747.8216896066072

## $\mu_0$

In [48]:
default.loc[default['default']=='No']['balance'].mean()

803.9437502338307

## $\sigma_1^2$

In [49]:
default.loc[default['default']=='Yes']['balance'].var()

116463.03454537454

## $\sigma_0^2$

In [50]:
default.loc[default['default']=='No']['balance'].var()

208370.553617943

### Weighted average of variance (this will be needed in LDA case)

In [65]:
(116463.03454537454 * 333 + 208370.553617943 * 9667) / 10000

205310.03323282645

### The weighted variance is different from the overall variance in entire 'balance' column.

In [64]:
default['balance'].values.var()

233956.7888983377

In [51]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

### In the following, we do not split the data into training and test subsets. Instead, we use the whole data set to fit the model. The purpose is to see what parameters are used in LDA and QDA.

In [54]:
x_default = default['balance'].values.reshape(-1,1)
y_default = default['default']

In [60]:
lda = LinearDiscriminantAnalysis(store_covariance=True)
lda.fit(x_default, y_default)

LinearDiscriminantAnalysis(store_covariance=True)

### Check if the following 2 numbers are the same as $\mu_0$ and $\mu_1$ ?

In [61]:
lda.means_

array([[ 803.94375023],
       [1747.82168961]])

### Check if the first number is the same as $\frac{N_0}{N_0+N_1}$ In LDA, we call it $\pi_0$, remember?

In [62]:
lda.priors_

array([0.9667, 0.0333])

### The variance $\sigma^2$ used in LDA is almost the same as the weighted vairance. Please check!

In [67]:
lda.covariance_

array([[205277.54987401]])

### Let us create a few test cases, and predict if these balances will lead to default.

In [73]:
test_balance = np.array([500, 1000, 1500, 2000, 2500]).reshape(-1,1)

In [74]:
lda.predict(test_balance)

array(['No', 'No', 'No', 'No', 'Yes'], dtype='<U3')

### Write a simple function to verify the above prediction

In [90]:
from scipy.stats import norm

In [92]:
norm.pdf(0.1)

0.3969525474770118

In [95]:
def test_lda(x):
    mu0 = lda.means_[0]
    mu1 = lda.means_[1]
    pi0 = lda.priors_[0]
    var = lda.covariance_[0]
    z0 = (x-mu0)/np.sqrt(var)
    z1 = (x-mu1)/np.sqrt(var)
    if pi0 * norm.pdf(z0) > (1-pi0) * norm.pdf(z1):
        return 'No'
    else:
        return 'Yes'

In [97]:
print(test_lda(test_balance[0]))

No


In [98]:
print(test_lda(test_balance[1]))

No


In [99]:
print(test_lda(test_balance[2]))

No


In [100]:
print(test_lda(test_balance[3]))

No


In [101]:
print(test_lda(test_balance[4]))

Yes


### Breaking down QDA parameters

In [75]:
qda = QuadraticDiscriminantAnalysis(store_covariance=True)

In [76]:
qda.fit(x_default, y_default)

QuadraticDiscriminantAnalysis(store_covariance=True)

In [77]:
qda.means_

array([[ 803.94375023],
       [1747.82168961]])

In [78]:
qda.priors_

array([0.9667, 0.0333])

In [79]:
qda.covariance_

[array([[208370.55361794]]), array([[116463.03454537]])]

In [80]:
qda.predict(test_balance)

array(['No', 'No', 'No', 'Yes', 'Yes'], dtype=object)

### Write down a simple function to test qda results

In [110]:
def test_qda(x):
    mu0 = qda.means_[0]
    mu1 = qda.means_[1]
    pi0 = qda.priors_[0]
    var0 = qda.covariance_[0][0]
    var1 = qda.covariance_[1][0]
    
    pdf0 = norm(mu0, np.sqrt(var0))
    pdf1 = norm(mu1, np.sqrt(var1))
    
    if pi0 * pdf0.pdf(x) > (1-pi0) * pdf1.pdf(x):
        return 'No'
    else:
        return 'Yes'

In [111]:
print(test_qda(test_balance[0]))

No


In [112]:
print(test_qda(test_balance[1]))

No


In [113]:
print(test_qda(test_balance[2]))

No


In [114]:
print(test_qda(test_balance[3]))

Yes


In [115]:
print(test_qda(test_balance[4]))

Yes


### Q24 k-nearest neighbor method

In [116]:
# In the question, it does not mention the parameter k so it is not clear how many neighbors need to be considered.

### Q25 Bayes rule

#### To know $p(y=1|x=1)$, we need to use the Bayes rule $p(y=1|x=1)=\frac{p(x=1|y=1)p(y=1)}{p(x=1)}$. The denominator $p(x=1)=p(x=1|y=1)p(y=1)+p(x=1|y=0)p(y=0)=ac+(1-b)(1-c)$. The numerator is $ac$. 

# Summary of what is new in this midterm review
 - Google bias_variance_decomp for knowing more details
 - we verified and breaked down LDA and QDA by looking into the application to default data set
 - what is pdf? probability density function
 - how to evaluate pdf using scipy.stats
 